:ems:
  :ems_foreman:
    :blacklisted_event_names: []
    :event_handling:
      :event_groups:
:ems_refresh:
  :foreman_configuration:
    :refresh_interval: 15.minutes
  :foreman_provisioning:
    :refresh_interval: 1.hour
:http_proxy:
  :foreman:
    :host:
    :password:
    :port:
    :user:
:workers:
  :ems_refresh_worker_foreman_configuration:
    :inherits_from: ems_refresh_worker
  :ems_refresh_worker_foreman_provisioning:
    :inherits_from: ems_refresh_worker
